const enc=new TextEncoder(),dec=new TextDecoder();
let schemaPromise;
const SCHEMA_VERSION=2;
const SCHEMA=`
CREATE TABLE IF NOT EXISTS app_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,phone TEXT,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'organizer',is_active INTEGER NOT NULL DEFAULT 1,failed_attempts INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS organizations(id TEXT PRIMARY KEY,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,owner_id TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS bingos(id TEXT PRIMARY KEY,name TEXT NOT NULL,description TEXT,organizer TEXT,event_date TEXT,start_time TEXT,location TEXT,image_url TEXT,total_cards INTEGER NOT NULL DEFAULT 0,card_price REAL NOT NULL DEFAULT 0,type TEXT NOT NULL DEFAULT '75',status TEXT NOT NULL DEFAULT 'draft',public_slug TEXT NOT NULL UNIQUE,observations TEXT,contact_info TEXT,organization_id TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS prizes(id TEXT PRIMARY KEY,name TEXT NOT NULL,description TEXT,value REAL,image_url TEXT,position INTEGER NOT NULL,win_type TEXT NOT NULL,bingo_id TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(bingo_id) REFERENCES bingos(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS cards(id TEXT PRIMARY KEY,card_number INTEGER NOT NULL,validation_code TEXT NOT NULL UNIQUE,qr_code_value TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'available',buyer_name TEXT,buyer_phone TEXT,seller_name TEXT,paid_value REAL,payment_method TEXT,sold_at TEXT,bingo_id TEXT NOT NULL,numbers_json TEXT NOT NULL DEFAULT '[]',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(bingo_id) REFERENCES bingos(id) ON DELETE CASCADE,UNIQUE(bingo_id,card_number));
CREATE TABLE IF NOT EXISTS sales(id TEXT PRIMARY KEY,buyer_name TEXT,buyer_phone TEXT,card_id TEXT NOT NULL UNIQUE,user_id TEXT,amount REAL NOT NULL,payment_method TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'sold',sold_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(card_id) REFERENCES cards(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS draw_numbers(id TEXT PRIMARY KEY,bingo_id TEXT NOT NULL,value INTEGER NOT NULL,position INTEGER NOT NULL,drawn_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(bingo_id) REFERENCES bingos(id) ON DELETE CASCADE,UNIQUE(bingo_id,value),UNIQUE(bingo_id,position));
CREATE TABLE IF NOT EXISTS audit_logs(id TEXT PRIMARY KEY,user_id TEXT,action TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT,details TEXT,ip_address TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE INDEX IF NOT EXISTS idx_bingos_org ON bingos(organization_id);
CREATE INDEX IF NOT EXISTS idx_cards_bingo ON cards(bingo_id);
CREATE INDEX IF NOT EXISTS idx_draw_bingo ON draw_numbers(bingo_id,position);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at DESC);
`;
const headers=(extra={})=>({'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'same-origin',...extra});
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:headers(extra)});
function b64(bytes){let s='';for(const b of bytes instanceof Uint8Array?bytes:new Uint8Array(bytes))s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
function unb64(v){const p=v.replace(/-/g,'+').replace(/_/g,'/')+'==='.slice((v.length+3)%4),s=atob(p);return Uint8Array.from(s,c=>c.charCodeAt(0))}
async function hmac(secret){return crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign','verify'])}
async function token(payload,secret){const now=Math.floor(Date.now()/1000),h=b64(enc.encode(JSON.stringify({alg:'HS256',typ:'JWT'}))),p=b64(enc.encode(JSON.stringify({...payload,iat:now,exp:now+604800}))),u=`${h}.${p}`,sig=await crypto.subtle.sign('HMAC',await hmac(secret),enc.encode(u));return `${u}.${b64(sig)}`}
async function verifyToken(value,secret){const p=value.split('.');if(p.length!==3)throw Error('token');const u=`${p[0]}.${p[1]}`;if(!await crypto.subtle.verify('HMAC',await hmac(secret),unb64(p[2]),enc.encode(u)))throw Error('token');const h=JSON.parse(dec.decode(unb64(p[0]))),body=JSON.parse(dec.decode(unb64(p[1])));if(h.alg!=='HS256'||h.typ!=='JWT'||!body.userId||!body.exp||body.exp<Math.floor(Date.now()/1000))throw Error('token');return body}
async function hashPassword(password){const iterations=120000,salt=crypto.getRandomValues(new Uint8Array(16)),key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations},key,256);return `pbkdf2$${iterations}$${b64(salt)}$${b64(bits)}`}
async function checkPassword(password,stored){const [kind,it,salt,want]=String(stored||'').split('$'),iterations=Number(it);if(kind!=='pbkdf2'||!Number.isSafeInteger(iterations)||iterations<10000)return false;const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']),got=new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:unb64(salt),iterations},key,256)),expected=unb64(want);if(got.length!==expected.length)return false;let d=0;for(let i=0;i<got.length;i++)d|=got[i]^expected[i];return d===0}
const clean=(v,n=500)=>{const s=String(v??'').trim();return s?s.slice(0,n):null};
const validEmail=v=>typeof v==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)&&v.length<=254;
const slugify=v=>(String(v||'bingo').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,40)||'bingo');
async function body(request){if(!(request.headers.get('content-type')||'').includes('application/json'))throw Object.assign(Error('Envie os dados em JSON.'),{status:415});if(Number(request.headers.get('content-length')||0)>1048576)throw Object.assign(Error('Requisição muito grande.'),{status:413});try{return await request.json()}catch{throw Object.assign(Error('JSON inválido.'),{status:400})}}
function sample(min,max,n){const a=Array.from({length:max-min+1},(_,i)=>min+i);for(let i=a.length-1;i>0;i--){const j=crypto.getRandomValues(new Uint32Array(1))[0]%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a.slice(0,n).sort((x,y)=>x-y)}
function card75(){const c=[sample(1,15,5),sample(16,30,5),sample(31,45,5),sample(46,60,5),sample(61,75,5)];return Array.from({length:5},(_,r)=>Array.from({length:5},(_,k)=>r===2&&k===2?0:c[k][r]))}
function card90(){for(let attempt=0;attempt<100;attempt++){const used=Array.from({length:3},()=>Array(9).fill(false)),rows=[0,0,0],cols=Array(9).fill(0);for(let c=0;c<9;c++){const can=[0,1,2].filter(r=>rows[r]<5),r=can[crypto.getRandomValues(new Uint32Array(1))[0]%can.length];used[r][c]=true;rows[r]++;cols[c]++}let guard=0;while(rows.some(n=>n<5)&&guard++<500){const rs=[0,1,2].filter(r=>rows[r]<5),r=rs[crypto.getRandomValues(new Uint32Array(1))[0]%rs.length],cs=Array.from({length:9},(_,c)=>c).filter(c=>!used[r][c]&&cols[c]<3);if(!cs.length)break;const c=cs[crypto.getRandomValues(new Uint32Array(1))[0]%cs.length];used[r][c]=true;rows[r]++;cols[c]++}if(!rows.every(n=>n===5))continue;const grid=Array.from({length:3},()=>Array(9).fill(0));for(let c=0;c<9;c++){const vals=sample(c===0?1:c*10,c===8?90:c*10+9,cols[c]);let x=0;for(let r=0;r<3;r++)if(used[r][c])grid[r][c]=vals[x++]}return grid}throw Error('Falha ao gerar cartela.')}
const makeNumbers=type=>String(type)==='90'?card90():card75();
const parseNumbers=v=>{try{const x=JSON.parse(v||'[]');return Array.isArray(x)?x:[]}catch{return[]}};
async function ensureSchema(env){if(!env.DB)throw Object.assign(Error('Banco D1 não configurado. Adicione um binding D1 chamado DB no Cloudflare.'),{status:503});if(!schemaPromise)schemaPromise=(async()=>{await env.DB.exec('CREATE TABLE IF NOT EXISTS app_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL)');const row=await env.DB.prepare("SELECT value FROM app_meta WHERE key='schema_version'").first();if(Number(row?.value||0)<SCHEMA_VERSION){await env.DB.exec(SCHEMA);const cols=await env.DB.prepare('PRAGMA table_info(cards)').all();if(!(cols.results||[]).some(c=>c.name==='numbers_json'))await env.DB.exec("ALTER TABLE cards ADD COLUMN numbers_json TEXT NOT NULL DEFAULT '[]'");await env.DB.prepare("INSERT INTO app_meta(key,value) VALUES('schema_version',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(String(SCHEMA_VERSION)).run();await env.DB.exec('PRAGMA optimize')}if(env.ADMIN_EMAIL&&env.ADMIN_PASSWORD){const email=String(env.ADMIN_EMAIL).trim().toLowerCase();if(validEmail(email)&&String(env.ADMIN_PASSWORD).length>=10&&!await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first()){const uid=crypto.randomUUID(),oid=crypto.randomUUID(),ph=await hashPassword(String(env.ADMIN_PASSWORD));await env.DB.batch([env.DB.prepare('INSERT INTO users(id,name,email,password_hash,role,is_active) VALUES(?,?,?,?,?,1)').bind(uid,clean(env.ADMIN_NAME,120)||'Administrador',email,ph,'admin'),env.DB.prepare('INSERT INTO organizations(id,name,slug,owner_id) VALUES(?,?,?,?)').bind(oid,clean(env.ORGANIZATION_NAME,120)||'Organização Bingo Fácil',`org-${uid.slice(0,8)}`,uid)])}}})().catch(e=>{schemaPromise=undefined;throw e});return schemaPromise}
async function user(request,env){const a=request.headers.get('authorization')||'';if(!a.startsWith('Bearer '))throw Object.assign(Error('Sessão inválida.'),{status:401});if(!env.JWT_SECRET||String(env.JWT_SECRET).length<32)throw Object.assign(Error('JWT_SECRET não configurado com segurança.'),{status:503});let p;try{p=await verifyToken(a.slice(7),env.JWT_SECRET)}catch{throw Object.assign(Error('Sessão expirada ou inválida.'),{status:401})}const u=await env.DB.prepare('SELECT id,name,email,role,is_active FROM users WHERE id=?').bind(p.userId).first();if(!u||!u.is_active)throw Object.assign(Error('Usuário não autorizado.'),{status:401});return u}
async function owned(env,uid,id){return env.DB.prepare('SELECT b.* FROM bingos b JOIN organizations o ON o.id=b.organization_id WHERE b.id=? AND o.owner_id=? LIMIT 1').bind(id,uid).first()}
async function audit(env,uid,action,type,id,details,request){await env.DB.prepare('INSERT INTO audit_logs(id,user_id,action,entity_type,entity_id,details,ip_address) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),uid||null,action,type,id||null,details||null,request.headers.get('CF-Connecting-IP')||null).run()}
async function route(request,env){await ensureSchema(env);const url=new URL(request.url),path=url.pathname.replace(/^\/api\/?/,'').replace(/\/$/,''),method=request.method.toUpperCase();
if(method==='GET'&&path==='health')return json({ok:true,service:'bingo-facil-cloudflare-api',schemaVersion:SCHEMA_VERSION,timestamp:new Date().toISOString()});
if(method==='GET'&&path==='setup/status'){const r=await env.DB.prepare('SELECT COUNT(*) count FROM users').first();return json({initialized:Number(r?.count||0)>0,adminEnvironmentConfigured:Boolean(env.ADMIN_EMAIL&&env.ADMIN_PASSWORD)})}
if(method==='POST'&&path==='auth/login'){const b=await body(request),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');if(!validEmail(email)||!password)return json({message:'Credenciais inválidas.'},401);const u=await env.DB.prepare('SELECT id,name,email,password_hash,role,is_active,failed_attempts,updated_at FROM users WHERE email=?').bind(email).first();if(!u||!u.is_active)return json({message:'Credenciais inválidas.'},401);const t=Date.parse(`${String(u.updated_at||'').replace(' ','T')}Z`);if(Number(u.failed_attempts||0)>=8&&Number.isFinite(t)&&Date.now()-t<900000)return json({message:'Muitas tentativas. Tente novamente em alguns minutos.'},429,{'Retry-After':'900'});if(Number(u.failed_attempts||0)>=8)await env.DB.prepare('UPDATE users SET failed_attempts=0,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(u.id).run();if(!await checkPassword(password,u.password_hash)){await env.DB.prepare('UPDATE users SET failed_attempts=failed_attempts+1,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(u.id).run();return json({message:'Credenciais inválidas.'},401)}if(!env.JWT_SECRET||String(env.JWT_SECRET).length<32)return json({message:'JWT_SECRET não configurado com segurança.'},503);await env.DB.prepare('UPDATE users SET failed_attempts=0,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(u.id).run();return json({token:await token({userId:u.id,role:u.role},env.JWT_SECRET),user:{id:u.id,name:u.name,email:u.email,role:u.role}})}
if(method==='GET'&&path==='auth/me'){const u=await user(request,env);return json({user:{id:u.id,name:u.name,email:u.email,role:u.role}})}
if(method==='POST'&&path==='auth/logout'){await user(request,env);return json({message:'Logout realizado.'})}
if(method==='GET'&&path==='bingos/dashboard'){const u=await user(request,env),o=await env.DB.prepare('SELECT id FROM organizations WHERE owner_id=? LIMIT 1').bind(u.id).first();if(!o)return json({message:'Organização não encontrada.'},404);const r=await env.DB.batch([env.DB.prepare('SELECT COUNT(*) count FROM bingos WHERE organization_id=?').bind(o.id),env.DB.prepare("SELECT COUNT(*) count FROM bingos WHERE organization_id=? AND status='active'").bind(o.id),env.DB.prepare("SELECT COUNT(*) count FROM bingos WHERE organization_id=? AND status='closed'").bind(o.id),env.DB.prepare('SELECT COUNT(*) count FROM cards c JOIN bingos b ON b.id=c.bingo_id WHERE b.organization_id=?').bind(o.id),env.DB.prepare("SELECT COUNT(*) count FROM cards c JOIN bingos b ON b.id=c.bingo_id WHERE b.organization_id=? AND c.status='sold'").bind(o.id),env.DB.prepare('SELECT COALESCE(SUM(s.amount),0) total FROM sales s JOIN cards c ON c.id=s.card_id JOIN bingos b ON b.id=c.bingo_id WHERE b.organization_id=?').bind(o.id)]),v=(i,k='count')=>Number(r[i].results?.[0]?.[k]||0);return json({stats:{totalBingos:v(0),activeBingos:v(1),closedBingos:v(2),totalCards:v(3),soldCards:v(4),availableCards:Math.max(v(3)-v(4),0),estimatedRevenue:v(5,'total'),participants:v(4)}})}
if(method==='GET'&&path==='bingos'){const u=await user(request,env),r=await env.DB.prepare(`SELECT b.*,(SELECT COUNT(*) FROM cards c WHERE c.bingo_id=b.id) cards_count,(SELECT COUNT(*) FROM prizes p WHERE p.bingo_id=b.id) prizes_count,(SELECT COUNT(*) FROM draw_numbers d WHERE d.bingo_id=b.id) drawn_count FROM bingos b JOIN organizations o ON o.id=b.organization_id WHERE o.owner_id=? ORDER BY b.created_at DESC`).bind(u.id).all();return json({bingos:r.results||[]})}
if(method==='POST'&&path==='bingos'){const u=await user(request,env),b=await body(request),name=String(b.name||'').trim().slice(0,120),total=Number(b.totalCards),price=Number(b.cardPrice);if(!name||!Number.isInteger(total)||total<1||total>100000||!Number.isFinite(price)||price<0)return json({message:'Dados inválidos.'},400);const o=await env.DB.prepare('SELECT id FROM organizations WHERE owner_id=? LIMIT 1').bind(u.id).first();if(!o)return json({message:'Organização não encontrada.'},404);const id=crypto.randomUUID(),slug=`${slugify(name)}-${Date.now().toString(36)}`;await env.DB.prepare('INSERT INTO bingos(id,name,description,organizer,event_date,start_time,location,total_cards,card_price,type,status,public_slug,contact_info,organization_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,name,clean(b.description,2000),clean(b.organizer,120),clean(b.eventDate,40),clean(b.startTime,20),clean(b.location,300),total,price,['75','90'].includes(String(b.type))?String(b.type):'75',['draft','active','closed'].includes(String(b.status))?String(b.status):'draft',slug,clean(b.contactInfo,500),o.id).run();await audit(env,u.id,'bingo_created','bingo',id,name,request);return json({bingo:await env.DB.prepare('SELECT * FROM bingos WHERE id=?').bind(id).first()},201)}
const pm=path.match(/^bingos\/([^/]+)\/prizes$/);if(method==='POST'&&pm){const u=await user(request,env),id=decodeURIComponent(pm[1]),bg=await owned(env,u.id,id),b=await body(request);if(!bg)return json({message:'Bingo não encontrado.'},404);if(!Array.isArray(b)||!b.length||b.length>40)return json({message:'Lista de prêmios inválida.'},400);const m=await env.DB.prepare('SELECT COALESCE(MAX(position),0) p FROM prizes WHERE bingo_id=?').bind(id).first(),stm=[];for(let i=0;i<b.length;i++){const p=b[i],name=String(p.name||'').trim().slice(0,120),value=p.value==null||p.value===''?null:Number(p.value);if(!name||(value!==null&&(!Number.isFinite(value)||value<0)))return json({message:'Prêmio inválido.'},400);stm.push(env.DB.prepare('INSERT INTO prizes(id,name,description,value,position,win_type,bingo_id) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),name,clean(p.description,1000),value,Number(m?.p||0)+i+1,'full_card',id))}await env.DB.batch(stm);return json({prizes:stm.length},201)}
if(method==='POST'&&path==='cards/generate'){const u=await user(request,env),b=await body(request),id=String(b.bingoId||''),requested=Number(b.quantity||1);if(!id||!Number.isInteger(requested)||requested<1||requested>400)return json({message:'A quantidade deve ser entre 1 e 400.'},400);const bg=await owned(env,u.id,id);if(!bg)return json({message:'Bingo não encontrado.'},404);const c=await env.DB.prepare('SELECT COUNT(*) count FROM cards WHERE bingo_id=?').bind(id).first(),existing=Number(c?.count||0),remaining=Math.max(Number(bg.total_cards||0)-existing,0);if(!remaining)return json({message:'Todas as cartelas previstas já foram geradas.'},409);const qty=Math.min(requested,remaining),cards=Array.from({length:qty},(_,i)=>({id:crypto.randomUUID(),cardNumber:existing+i+1,validationCode:crypto.randomUUID().replace(/-/g,'').slice(0,10).toUpperCase(),qrCodeValue:crypto.randomUUID(),numbers:makeNumbers(bg.type)})),stm=[];for(let start=0;start<cards.length;start+=12){const chunk=cards.slice(start,start+12),ph=chunk.map(()=>'(?,?,?,?,?,?,?,?)').join(','),vals=chunk.flatMap(c=>[c.id,c.cardNumber,c.validationCode,c.qrCodeValue,'available','Sistema',id,JSON.stringify(c.numbers)]);stm.push(env.DB.prepare(`INSERT INTO cards(id,card_number,validation_code,qr_code_value,status,seller_name,bingo_id,numbers_json) VALUES ${ph}`).bind(...vals))}await env.DB.batch(stm);return json({created:qty,remaining:remaining-qty,cards},201)}
if(method==='POST'&&path==='cards/sell'){const u=await user(request,env),b=await body(request),id=String(b.bingoId||''),num=Number(b.cardNumber),bg=await owned(env,u.id,id);if(!bg)return json({message:'Bingo não encontrado.'},404);const c=await env.DB.prepare('SELECT id,status FROM cards WHERE bingo_id=? AND card_number=?').bind(id,num).first();if(!c)return json({message:'Cartela não encontrada.'},404);if(c.status==='sold')return json({message:'Esta cartela já foi vendida.'},409);const amount=b.paidValue==null||b.paidValue===''?Number(bg.card_price||0):Number(b.paidValue);if(!Number.isFinite(amount)||amount<0)return json({message:'Valor inválido.'},400);const sid=crypto.randomUUID(),buyer=clean(b.buyerName,120),phone=clean(b.buyerPhone,40),pay=clean(b.paymentMethod,40)||'dinheiro';await env.DB.batch([env.DB.prepare("UPDATE cards SET status='sold',buyer_name=?,buyer_phone=?,paid_value=?,payment_method=?,sold_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status<>'sold'").bind(buyer,phone,amount,pay,c.id),env.DB.prepare('INSERT INTO sales(id,buyer_name,buyer_phone,card_id,user_id,amount,payment_method,status) VALUES(?,?,?,?,?,?,?,?)').bind(sid,buyer,phone,c.id,u.id,amount,pay,'sold')]);return json({message:'Venda registrada.',saleId:sid})}
const dm=path.match(/^bingos\/([^/]+)\/draw$/);if(dm&&method==='GET'){const u=await user(request,env),id=decodeURIComponent(dm[1]),bg=await owned(env,u.id,id);if(!bg)return json({message:'Bingo não encontrado.'},404);const r=await env.DB.prepare('SELECT value,position,drawn_at FROM draw_numbers WHERE bingo_id=? ORDER BY position').bind(id).all();return json({numbers:r.results||[],maxNumber:String(bg.type)==='90'?90:75})}
if(dm&&method==='POST'){const u=await user(request,env),id=decodeURIComponent(dm[1]),bg=await owned(env,u.id,id);if(!bg)return json({message:'Bingo não encontrado.'},404);const max=String(bg.type)==='90'?90:75,r=await env.DB.prepare('SELECT value FROM draw_numbers WHERE bingo_id=?').bind(id).all(),used=new Set((r.results||[]).map(x=>Number(x.value)));if(used.size>=max)return json({message:'Todos os números já foram sorteados.'},409);const a=Array.from({length:max},(_,i)=>i+1).filter(n=>!used.has(n)),value=a[crypto.getRandomValues(new Uint32Array(1))[0]%a.length],position=used.size+1;await env.DB.prepare('INSERT INTO draw_numbers(id,bingo_id,value,position) VALUES(?,?,?,?)').bind(crypto.randomUUID(),id,value,position).run();return json({value,position,remaining:max-position},201)}
const rm=path.match(/^bingos\/([^/]+)\/draw\/reset$/);if(rm&&method==='POST'){const u=await user(request,env),id=decodeURIComponent(rm[1]);if(!await owned(env,u.id,id))return json({message:'Bingo não encontrado.'},404);await env.DB.prepare('DELETE FROM draw_numbers WHERE bingo_id=?').bind(id).run();return json({message:'Sorteio reiniciado.'})}
const vm=path.match(/^cards\/verify\/([^/]+)$/);if(vm&&method==='GET'){const q=decodeURIComponent(vm[1]),c=await env.DB.prepare('SELECT c.id,c.card_number,c.validation_code,c.status,c.numbers_json,b.name bingo_name,b.public_slug FROM cards c JOIN bingos b ON b.id=c.bingo_id WHERE c.qr_code_value=? OR c.validation_code=? LIMIT 1').bind(q,q).first();if(!c)return json({valid:false,message:'Cartela não encontrada.'},404);return json({valid:true,card:{id:c.id,number:c.card_number,validationCode:c.validation_code,status:c.status,bingo:c.bingo_name,publicSlug:c.public_slug,numbers:parseNumbers(c.numbers_json)}})}
const pub=path.match(/^public\/bingo\/([^/]+)$/);if(pub&&method==='GET'){const bg=await env.DB.prepare('SELECT * FROM bingos WHERE public_slug=?').bind(decodeURIComponent(pub[1])).first();if(!bg)return json({message:'Evento não encontrado.'},404);const [p,d]=await env.DB.batch([env.DB.prepare('SELECT id,name,description,value,position,win_type FROM prizes WHERE bingo_id=? ORDER BY position').bind(bg.id),env.DB.prepare('SELECT value,position,drawn_at FROM draw_numbers WHERE bingo_id=? ORDER BY position').bind(bg.id)]);return json({bingo:{...bg,prizes:p.results||[],drawnNumbers:d.results||[]}})}
return json({message:'Rota não encontrada.'},404)}
export async function onRequest({request,env}){const origin=new URL(request.url).origin;if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Headers':'Authorization, Content-Type','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Max-Age':'86400','Vary':'Origin'}});try{const r=await route(request,env),h=new Headers(r.headers);h.set('Access-Control-Allow-Origin',origin);h.set('Vary','Origin');return new Response(r.body,{status:r.status,statusText:r.statusText,headers:h})}catch(e){console.error('API error',e);const s=Number(e?.status||500);return json({message:s>=500?'Não foi possível concluir esta operação.':(e?.message||'Não foi possível concluir esta operação.')},s)}}
